#############################################################################
# Makefile for building: dudley
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Sep 27 15:53:26 2010
# Project:  dudley.pro
# Template: app
# Command: /home/rob/qtsdk-2010.02/qt/bin/qmake -unix -o Makefile dudley.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2010.02/qt/mkspecs/linux-g++-64 -I. -I../../qtsdk-2010.02/qt/include/QtCore -I../../qtsdk-2010.02/qt/include/QtNetwork -I../../qtsdk-2010.02/qt/include/QtGui -I../../qtsdk-2010.02/qt/include/QtXml -I../../qtsdk-2010.02/qt/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/rob/qtsdk-2010.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/rob/qtsdk-2010.02/qt/lib -lQtXml -L/home/rob/qtsdk-2010.02/qt/lib -lQtGui -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/rob/qtsdk-2010.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		fileinfo.cpp \
		filerepostate.cpp \
		filerepostatelogger.cpp \
		filerepo.cpp \
		workingfilerepo.cpp \
		storagefilerepo.cpp \
		output.cpp \
		server.cpp \
		mainwindow.cpp \
		repodialog.cpp \
		repotablemodel.cpp \
		httprequest.cpp \
		httpresponse.cpp \
		mime/freedesktopmime.cpp \
		httpclientfilerepo.cpp moc_filerepostate.cpp \
		moc_filerepo.cpp \
		moc_storagefilerepo.cpp \
		moc_server.cpp \
		moc_mainwindow.cpp \
		moc_repodialog.cpp \
		moc_repotablemodel.cpp \
		moc_freedesktopmime.cpp \
		moc_httpclientfilerepo.cpp \
		qrc_icon.cpp \
		qrc_freedesktopmime.cpp
OBJECTS       = main.o \
		fileinfo.o \
		filerepostate.o \
		filerepostatelogger.o \
		filerepo.o \
		workingfilerepo.o \
		storagefilerepo.o \
		output.o \
		server.o \
		mainwindow.o \
		repodialog.o \
		repotablemodel.o \
		httprequest.o \
		httpresponse.o \
		freedesktopmime.o \
		httpclientfilerepo.o \
		moc_filerepostate.o \
		moc_filerepo.o \
		moc_storagefilerepo.o \
		moc_server.o \
		moc_mainwindow.o \
		moc_repodialog.o \
		moc_repotablemodel.o \
		moc_freedesktopmime.o \
		moc_httpclientfilerepo.o \
		qrc_icon.o \
		qrc_freedesktopmime.o
DIST          = ../../qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/release.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		dudley.pro
QMAKE_TARGET  = dudley
DESTDIR       = 
TARGET        = dudley

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_repodialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dudley.pro  ../../qtsdk-2010.02/qt/mkspecs/linux-g++-64/qmake.conf ../../qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/release.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		/home/rob/qtsdk-2010.02/qt/lib/libQtXml.prl \
		/home/rob/qtsdk-2010.02/qt/lib/libQtCore.prl \
		/home/rob/qtsdk-2010.02/qt/lib/libQtGui.prl \
		/home/rob/qtsdk-2010.02/qt/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile dudley.pro
../../qtsdk-2010.02/qt/mkspecs/common/g++.conf:
../../qtsdk-2010.02/qt/mkspecs/common/unix.conf:
../../qtsdk-2010.02/qt/mkspecs/common/linux.conf:
../../qtsdk-2010.02/qt/mkspecs/qconfig.pri:
../../qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2010.02/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2010.02/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2010.02/qt/mkspecs/features/release.prf:
../../qtsdk-2010.02/qt/mkspecs/features/default_post.prf:
../../qtsdk-2010.02/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2010.02/qt/mkspecs/features/qt.prf:
../../qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2010.02/qt/mkspecs/features/moc.prf:
../../qtsdk-2010.02/qt/mkspecs/features/resources.prf:
../../qtsdk-2010.02/qt/mkspecs/features/uic.prf:
../../qtsdk-2010.02/qt/mkspecs/features/yacc.prf:
../../qtsdk-2010.02/qt/mkspecs/features/lex.prf:
../../qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf:
/home/rob/qtsdk-2010.02/qt/lib/libQtXml.prl:
/home/rob/qtsdk-2010.02/qt/lib/libQtCore.prl:
/home/rob/qtsdk-2010.02/qt/lib/libQtGui.prl:
/home/rob/qtsdk-2010.02/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile dudley.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dudley1.0.0 || $(MKDIR) .tmp/dudley1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dudley1.0.0/ && $(COPY_FILE) --parents fileinfo.h filerepostate.h filerepostatelogger.h filerepo.h workingfilerepo.h storagefilerepo.h output.h server.h mainwindow.h repodialog.h repotablemodel.h httprequest.h httpresponse.h mime/freedesktopmime.h httpclientfilerepo.h .tmp/dudley1.0.0/ && $(COPY_FILE) --parents icon.qrc mime/freedesktopmime.qrc mime/freedesktopmime.qrc .tmp/dudley1.0.0/ && $(COPY_FILE) --parents main.cpp fileinfo.cpp filerepostate.cpp filerepostatelogger.cpp filerepo.cpp workingfilerepo.cpp storagefilerepo.cpp output.cpp server.cpp mainwindow.cpp repodialog.cpp repotablemodel.cpp httprequest.cpp httpresponse.cpp mime/freedesktopmime.cpp httpclientfilerepo.cpp .tmp/dudley1.0.0/ && $(COPY_FILE) --parents mainwindow.ui repodialog.ui .tmp/dudley1.0.0/ && (cd `dirname .tmp/dudley1.0.0` && $(TAR) dudley1.0.0.tar dudley1.0.0 && $(COMPRESS) dudley1.0.0.tar) && $(MOVE) `dirname .tmp/dudley1.0.0`/dudley1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dudley1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_filerepostate.cpp moc_filerepo.cpp moc_storagefilerepo.cpp moc_server.cpp moc_mainwindow.cpp moc_repodialog.cpp moc_repotablemodel.cpp moc_freedesktopmime.cpp moc_httpclientfilerepo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_filerepostate.cpp moc_filerepo.cpp moc_storagefilerepo.cpp moc_server.cpp moc_mainwindow.cpp moc_repodialog.cpp moc_repotablemodel.cpp moc_freedesktopmime.cpp moc_httpclientfilerepo.cpp
moc_filerepostate.cpp: fileinfo.h \
		filerepostate.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) filerepostate.h -o moc_filerepostate.cpp

moc_filerepo.cpp: filerepostate.h \
		fileinfo.h \
		filerepo.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) filerepo.h -o moc_filerepo.cpp

moc_storagefilerepo.cpp: filerepo.h \
		filerepostate.h \
		fileinfo.h \
		storagefilerepo.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) storagefilerepo.h -o moc_storagefilerepo.cpp

moc_server.cpp: fileinfo.h \
		server.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) server.h -o moc_server.cpp

moc_mainwindow.cpp: server.h \
		fileinfo.h \
		repodialog.h \
		repotablemodel.h \
		filerepo.h \
		filerepostate.h \
		mainwindow.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_repodialog.cpp: repodialog.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) repodialog.h -o moc_repodialog.cpp

moc_repotablemodel.cpp: filerepo.h \
		filerepostate.h \
		fileinfo.h \
		repotablemodel.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) repotablemodel.h -o moc_repotablemodel.cpp

moc_freedesktopmime.cpp: mime/freedesktopmime.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) mime/freedesktopmime.h -o moc_freedesktopmime.cpp

moc_httpclientfilerepo.cpp: filerepostate.h \
		fileinfo.h \
		filerepo.h \
		httpclientfilerepo.h
	/home/rob/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) httpclientfilerepo.h -o moc_httpclientfilerepo.cpp

compiler_rcc_make_all: qrc_icon.cpp qrc_freedesktopmime.cpp qrc_freedesktopmime.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icon.cpp qrc_freedesktopmime.cpp qrc_freedesktopmime.cpp
qrc_icon.cpp: icon.qrc \
		dino1.png
	/home/rob/qtsdk-2010.02/qt/bin/rcc -name icon icon.qrc -o qrc_icon.cpp

qrc_freedesktopmime.cpp: mime/freedesktopmime.qrc \
		mime/freedesktop.org.xml
	/home/rob/qtsdk-2010.02/qt/bin/rcc -name freedesktopmime mime/freedesktopmime.qrc -o qrc_freedesktopmime.cpp

qrc_freedesktopmime.cpp: mime/freedesktopmime.qrc \
		mime/freedesktop.org.xml
	/home/rob/qtsdk-2010.02/qt/bin/rcc -name freedesktopmime mime/freedesktopmime.qrc -o qrc_freedesktopmime.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_repodialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_repodialog.h
ui_mainwindow.h: mainwindow.ui
	/home/rob/qtsdk-2010.02/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_repodialog.h: repodialog.ui
	/home/rob/qtsdk-2010.02/qt/bin/uic repodialog.ui -o ui_repodialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp filerepo.h \
		filerepostate.h \
		fileinfo.h \
		filerepostatelogger.h \
		workingfilerepo.h \
		output.h \
		mainwindow.h \
		server.h \
		repodialog.h \
		repotablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

fileinfo.o: fileinfo.cpp fileinfo.h \
		mime/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileinfo.o fileinfo.cpp

filerepostate.o: filerepostate.cpp filerepostate.h \
		fileinfo.h \
		filerepostatelogger.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filerepostate.o filerepostate.cpp

filerepostatelogger.o: filerepostatelogger.cpp filerepostatelogger.h \
		fileinfo.h \
		filerepostate.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filerepostatelogger.o filerepostatelogger.cpp

filerepo.o: filerepo.cpp filerepo.h \
		filerepostate.h \
		fileinfo.h \
		filerepostatelogger.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filerepo.o filerepo.cpp

workingfilerepo.o: workingfilerepo.cpp workingfilerepo.h \
		filerepostatelogger.h \
		fileinfo.h \
		filerepostate.h \
		filerepo.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workingfilerepo.o workingfilerepo.cpp

storagefilerepo.o: storagefilerepo.cpp storagefilerepo.h \
		filerepo.h \
		filerepostate.h \
		fileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o storagefilerepo.o storagefilerepo.cpp

output.o: output.cpp output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o output.o output.cpp

server.o: server.cpp server.h \
		fileinfo.h \
		output.h \
		httprequest.h \
		httpresponse.h \
		repotablemodel.h \
		filerepo.h \
		filerepostate.h \
		filerepostatelogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o server.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		server.h \
		fileinfo.h \
		repodialog.h \
		repotablemodel.h \
		filerepo.h \
		filerepostate.h \
		ui_mainwindow.h \
		output.h \
		workingfilerepo.h \
		filerepostatelogger.h \
		httpclientfilerepo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

repodialog.o: repodialog.cpp repodialog.h \
		ui_repodialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repodialog.o repodialog.cpp

repotablemodel.o: repotablemodel.cpp repotablemodel.h \
		filerepo.h \
		filerepostate.h \
		fileinfo.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repotablemodel.o repotablemodel.cpp

httprequest.o: httprequest.cpp httprequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httprequest.o httprequest.cpp

httpresponse.o: httpresponse.cpp httpresponse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpresponse.o httpresponse.cpp

freedesktopmime.o: mime/freedesktopmime.cpp mime/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o freedesktopmime.o mime/freedesktopmime.cpp

httpclientfilerepo.o: httpclientfilerepo.cpp httpclientfilerepo.h \
		filerepostate.h \
		fileinfo.h \
		filerepo.h \
		output.h \
		filerepostatelogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpclientfilerepo.o httpclientfilerepo.cpp

moc_filerepostate.o: moc_filerepostate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filerepostate.o moc_filerepostate.cpp

moc_filerepo.o: moc_filerepo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filerepo.o moc_filerepo.cpp

moc_storagefilerepo.o: moc_storagefilerepo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_storagefilerepo.o moc_storagefilerepo.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_repodialog.o: moc_repodialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_repodialog.o moc_repodialog.cpp

moc_repotablemodel.o: moc_repotablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_repotablemodel.o moc_repotablemodel.cpp

moc_freedesktopmime.o: moc_freedesktopmime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_freedesktopmime.o moc_freedesktopmime.cpp

moc_httpclientfilerepo.o: moc_httpclientfilerepo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpclientfilerepo.o moc_httpclientfilerepo.cpp

qrc_icon.o: qrc_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icon.o qrc_icon.cpp

qrc_freedesktopmime.o: qrc_freedesktopmime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_freedesktopmime.o qrc_freedesktopmime.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

