#############################################################################
# Makefile for building: dudley
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Jan 16 21:16:13 2011
# Project:  dudley.pro
# Template: app
# Command: /home/rob/qtsdk-2010.05/qt/bin/qmake -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile dudley.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2010.05/qt/mkspecs/linux-g++-64 -I. -I../../qtsdk-2010.05/qt/include/QtCore -I../../qtsdk-2010.05/qt/include/QtNetwork -I../../qtsdk-2010.05/qt/include/QtGui -I../../qtsdk-2010.05/qt/include -I../qjson/src -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/rob/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/rob/qtsdk-2010.05/qt/lib -L/home/rob/src/qjson/lib -lqjson -lQtGui -L/home/rob/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/rob/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		fileinfo.cpp \
		state.cpp \
		statelogger.cpp \
		localdiskrepo.cpp \
		localstoragerepo.cpp \
		output.cpp \
		httpserver.cpp \
		mainwindow.cpp \
		repodialog.cpp \
		repomodel.cpp \
		httprequest.cpp \
		httpresponse.cpp \
		httpclientrepo.cpp \
		mimetypefinder.cpp \
		filetransfer.cpp \
		filetransfermanager.cpp \
		httpmessage.cpp \
		repo.cpp \
		httpcontroller.cpp \
		httpview.cpp \
		statediff.cpp \
		statediffop.cpp moc_fileinfo.cpp \
		moc_state.cpp \
		moc_statelogger.cpp \
		moc_localdiskrepo.cpp \
		moc_localstoragerepo.cpp \
		moc_output.cpp \
		moc_httpserver.cpp \
		moc_mainwindow.cpp \
		moc_repodialog.cpp \
		moc_repomodel.cpp \
		moc_httprequest.cpp \
		moc_httpresponse.cpp \
		moc_httpclientrepo.cpp \
		moc_filetransfer.cpp \
		moc_filetransfermanager.cpp \
		moc_httpmessage.cpp \
		moc_repo.cpp \
		moc_readoncebuffer.cpp \
		moc_httpcontroller.cpp \
		moc_statediff.cpp \
		qrc_icon.cpp
OBJECTS       = main.o \
		fileinfo.o \
		state.o \
		statelogger.o \
		localdiskrepo.o \
		localstoragerepo.o \
		output.o \
		httpserver.o \
		mainwindow.o \
		repodialog.o \
		repomodel.o \
		httprequest.o \
		httpresponse.o \
		httpclientrepo.o \
		mimetypefinder.o \
		filetransfer.o \
		filetransfermanager.o \
		httpmessage.o \
		repo.o \
		httpcontroller.o \
		httpview.o \
		statediff.o \
		statediffop.o \
		moc_fileinfo.o \
		moc_state.o \
		moc_statelogger.o \
		moc_localdiskrepo.o \
		moc_localstoragerepo.o \
		moc_output.o \
		moc_httpserver.o \
		moc_mainwindow.o \
		moc_repodialog.o \
		moc_repomodel.o \
		moc_httprequest.o \
		moc_httpresponse.o \
		moc_httpclientrepo.o \
		moc_filetransfer.o \
		moc_filetransfermanager.o \
		moc_httpmessage.o \
		moc_repo.o \
		moc_readoncebuffer.o \
		moc_httpcontroller.o \
		moc_statediff.o \
		qrc_icon.o
DIST          = ../../qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		dudley.pro
QMAKE_TARGET  = dudley
DESTDIR       = 
TARGET        = dudley

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_repodialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dudley.pro  ../../qtsdk-2010.05/qt/mkspecs/linux-g++-64/qmake.conf ../../qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/home/rob/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/home/rob/qtsdk-2010.05/qt/lib/libQtCore.prl \
		/home/rob/qtsdk-2010.05/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile dudley.pro
../../qtsdk-2010.05/qt/mkspecs/common/g++.conf:
../../qtsdk-2010.05/qt/mkspecs/common/unix.conf:
../../qtsdk-2010.05/qt/mkspecs/common/linux.conf:
../../qtsdk-2010.05/qt/mkspecs/qconfig.pri:
../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2010.05/qt/mkspecs/features/debug.prf:
../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2010.05/qt/mkspecs/features/qt.prf:
../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2010.05/qt/mkspecs/features/moc.prf:
../../qtsdk-2010.05/qt/mkspecs/features/resources.prf:
../../qtsdk-2010.05/qt/mkspecs/features/uic.prf:
../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
../../qtsdk-2010.05/qt/mkspecs/features/lex.prf:
../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/home/rob/qtsdk-2010.05/qt/lib/libQtGui.prl:
/home/rob/qtsdk-2010.05/qt/lib/libQtCore.prl:
/home/rob/qtsdk-2010.05/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile dudley.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dudley1.0.0 || $(MKDIR) .tmp/dudley1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dudley1.0.0/ && $(COPY_FILE) --parents fileinfo.h state.h statelogger.h localdiskrepo.h localstoragerepo.h output.h httpserver.h mainwindow.h repodialog.h repomodel.h httprequest.h httpresponse.h httpclientrepo.h mimetypefinder.h filetransfer.h filetransfermanager.h httpmessage.h repo.h readoncebuffer.h httpcontroller.h httpview.h statediff.h statediffop.h .tmp/dudley1.0.0/ && $(COPY_FILE) --parents icon.qrc .tmp/dudley1.0.0/ && $(COPY_FILE) --parents main.cpp fileinfo.cpp state.cpp statelogger.cpp localdiskrepo.cpp localstoragerepo.cpp output.cpp httpserver.cpp mainwindow.cpp repodialog.cpp repomodel.cpp httprequest.cpp httpresponse.cpp httpclientrepo.cpp mimetypefinder.cpp filetransfer.cpp filetransfermanager.cpp httpmessage.cpp repo.cpp httpcontroller.cpp httpview.cpp statediff.cpp statediffop.cpp .tmp/dudley1.0.0/ && $(COPY_FILE) --parents mainwindow.ui repodialog.ui .tmp/dudley1.0.0/ && (cd `dirname .tmp/dudley1.0.0` && $(TAR) dudley1.0.0.tar dudley1.0.0 && $(COMPRESS) dudley1.0.0.tar) && $(MOVE) `dirname .tmp/dudley1.0.0`/dudley1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dudley1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_fileinfo.cpp moc_state.cpp moc_statelogger.cpp moc_localdiskrepo.cpp moc_localstoragerepo.cpp moc_output.cpp moc_httpserver.cpp moc_mainwindow.cpp moc_repodialog.cpp moc_repomodel.cpp moc_httprequest.cpp moc_httpresponse.cpp moc_httpclientrepo.cpp moc_filetransfer.cpp moc_filetransfermanager.cpp moc_httpmessage.cpp moc_repo.cpp moc_readoncebuffer.cpp moc_httpcontroller.cpp moc_statediff.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fileinfo.cpp moc_state.cpp moc_statelogger.cpp moc_localdiskrepo.cpp moc_localstoragerepo.cpp moc_output.cpp moc_httpserver.cpp moc_mainwindow.cpp moc_repodialog.cpp moc_repomodel.cpp moc_httprequest.cpp moc_httpresponse.cpp moc_httpclientrepo.cpp moc_filetransfer.cpp moc_filetransfermanager.cpp moc_httpmessage.cpp moc_repo.cpp moc_readoncebuffer.cpp moc_httpcontroller.cpp moc_statediff.cpp
moc_fileinfo.cpp: mimetypefinder.h \
		fileinfo.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) fileinfo.h -o moc_fileinfo.cpp

moc_state.cpp: fileinfo.h \
		mimetypefinder.h \
		state.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) state.h -o moc_state.cpp

moc_statelogger.cpp: fileinfo.h \
		mimetypefinder.h \
		state.h \
		statelogger.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) statelogger.h -o moc_statelogger.cpp

moc_localdiskrepo.cpp: statelogger.h \
		fileinfo.h \
		mimetypefinder.h \
		state.h \
		repo.h \
		localdiskrepo.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) localdiskrepo.h -o moc_localdiskrepo.cpp

moc_localstoragerepo.cpp: repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		localstoragerepo.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) localstoragerepo.h -o moc_localstoragerepo.cpp

moc_output.cpp: output.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) output.h -o moc_output.cpp

moc_httpserver.cpp: fileinfo.h \
		mimetypefinder.h \
		httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		httpcontroller.h \
		httpresponse.h \
		repo.h \
		state.h \
		repomodel.h \
		filetransfermanager.h \
		filetransfer.h \
		httpserver.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) httpserver.h -o moc_httpserver.cpp

moc_mainwindow.cpp: httpserver.h \
		fileinfo.h \
		mimetypefinder.h \
		httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		httpcontroller.h \
		httpresponse.h \
		repo.h \
		state.h \
		repomodel.h \
		filetransfermanager.h \
		filetransfer.h \
		repodialog.h \
		output.h \
		mainwindow.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_repodialog.cpp: repodialog.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) repodialog.h -o moc_repodialog.cpp

moc_repomodel.cpp: repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		repomodel.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) repomodel.h -o moc_repomodel.cpp

moc_httprequest.cpp: httpmessage.h \
		readoncebuffer.h \
		httprequest.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) httprequest.h -o moc_httprequest.cpp

moc_httpresponse.cpp: httpmessage.h \
		readoncebuffer.h \
		httpresponse.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) httpresponse.h -o moc_httpresponse.cpp

moc_httpclientrepo.cpp: state.h \
		fileinfo.h \
		mimetypefinder.h \
		repo.h \
		httpclientrepo.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) httpclientrepo.h -o moc_httpclientrepo.cpp

moc_filetransfer.cpp: fileinfo.h \
		mimetypefinder.h \
		filetransfer.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) filetransfer.h -o moc_filetransfer.cpp

moc_filetransfermanager.cpp: filetransfer.h \
		fileinfo.h \
		mimetypefinder.h \
		filetransfermanager.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) filetransfermanager.h -o moc_filetransfermanager.cpp

moc_httpmessage.cpp: readoncebuffer.h \
		httpmessage.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) httpmessage.h -o moc_httpmessage.cpp

moc_repo.cpp: state.h \
		fileinfo.h \
		mimetypefinder.h \
		repo.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) repo.h -o moc_repo.cpp

moc_readoncebuffer.cpp: readoncebuffer.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) readoncebuffer.h -o moc_readoncebuffer.cpp

moc_httpcontroller.cpp: httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		httpresponse.h \
		repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		repomodel.h \
		filetransfermanager.h \
		filetransfer.h \
		httpcontroller.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) httpcontroller.h -o moc_httpcontroller.cpp

moc_statediff.cpp: statediffop.h \
		statediff.h
	/home/rob/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) statediff.h -o moc_statediff.cpp

compiler_rcc_make_all: qrc_icon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icon.cpp
qrc_icon.cpp: icon.qrc \
		dino1.png \
		uploadform.html \
		mimetypes.txt
	/home/rob/qtsdk-2010.05/qt/bin/rcc -name icon icon.qrc -o qrc_icon.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_repodialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_repodialog.h
ui_mainwindow.h: mainwindow.ui
	/home/rob/qtsdk-2010.05/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_repodialog.h: repodialog.ui
	/home/rob/qtsdk-2010.05/qt/bin/uic repodialog.ui -o ui_repodialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		statelogger.h \
		localdiskrepo.h \
		output.h \
		mainwindow.h \
		httpserver.h \
		httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		httpcontroller.h \
		httpresponse.h \
		repomodel.h \
		filetransfermanager.h \
		filetransfer.h \
		repodialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

fileinfo.o: fileinfo.cpp fileinfo.h \
		mimetypefinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileinfo.o fileinfo.cpp

state.o: state.cpp state.h \
		fileinfo.h \
		mimetypefinder.h \
		statelogger.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o state.o state.cpp

statelogger.o: statelogger.cpp statelogger.h \
		fileinfo.h \
		mimetypefinder.h \
		state.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statelogger.o statelogger.cpp

localdiskrepo.o: localdiskrepo.cpp repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		localdiskrepo.h \
		statelogger.h \
		output.h \
		filetransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localdiskrepo.o localdiskrepo.cpp

localstoragerepo.o: localstoragerepo.cpp localstoragerepo.h \
		repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localstoragerepo.o localstoragerepo.cpp

output.o: output.cpp output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o output.o output.cpp

httpserver.o: httpserver.cpp output.h \
		httpserver.h \
		fileinfo.h \
		mimetypefinder.h \
		httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		httpcontroller.h \
		httpresponse.h \
		repo.h \
		state.h \
		repomodel.h \
		filetransfermanager.h \
		filetransfer.h \
		statelogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpserver.o httpserver.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		httpserver.h \
		fileinfo.h \
		mimetypefinder.h \
		httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		httpcontroller.h \
		httpresponse.h \
		repo.h \
		state.h \
		repomodel.h \
		filetransfermanager.h \
		filetransfer.h \
		repodialog.h \
		output.h \
		ui_mainwindow.h \
		localdiskrepo.h \
		statelogger.h \
		httpclientrepo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

repodialog.o: repodialog.cpp repodialog.h \
		ui_repodialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repodialog.o repodialog.cpp

repomodel.o: repomodel.cpp repomodel.h \
		repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repomodel.o repomodel.cpp

httprequest.o: httprequest.cpp httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httprequest.o httprequest.cpp

httpresponse.o: httpresponse.cpp httpresponse.h \
		httpmessage.h \
		readoncebuffer.h \
		output.h \
		fileinfo.h \
		mimetypefinder.h \
		repo.h \
		state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpresponse.o httpresponse.cpp

httpclientrepo.o: httpclientrepo.cpp httpclientrepo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		repo.h \
		output.h \
		statelogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpclientrepo.o httpclientrepo.cpp

mimetypefinder.o: mimetypefinder.cpp mimetypefinder.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimetypefinder.o mimetypefinder.cpp

filetransfer.o: filetransfer.cpp filetransfer.h \
		fileinfo.h \
		mimetypefinder.h \
		repo.h \
		state.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filetransfer.o filetransfer.cpp

filetransfermanager.o: filetransfermanager.cpp filetransfermanager.h \
		filetransfer.h \
		fileinfo.h \
		mimetypefinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filetransfermanager.o filetransfermanager.cpp

httpmessage.o: httpmessage.cpp httpmessage.h \
		readoncebuffer.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpmessage.o httpmessage.cpp

repo.o: repo.cpp repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		statelogger.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repo.o repo.cpp

httpcontroller.o: httpcontroller.cpp httpcontroller.h \
		httprequest.h \
		httpmessage.h \
		readoncebuffer.h \
		httpresponse.h \
		repo.h \
		state.h \
		fileinfo.h \
		mimetypefinder.h \
		repomodel.h \
		filetransfermanager.h \
		filetransfer.h \
		statelogger.h \
		output.h \
		httpview.h \
		httpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpcontroller.o httpcontroller.cpp

httpview.o: httpview.cpp httpview.h \
		fileinfo.h \
		mimetypefinder.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpview.o httpview.cpp

statediff.o: statediff.cpp statediff.h \
		statediffop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statediff.o statediff.cpp

statediffop.o: statediffop.cpp statediffop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statediffop.o statediffop.cpp

moc_fileinfo.o: moc_fileinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fileinfo.o moc_fileinfo.cpp

moc_state.o: moc_state.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_state.o moc_state.cpp

moc_statelogger.o: moc_statelogger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statelogger.o moc_statelogger.cpp

moc_localdiskrepo.o: moc_localdiskrepo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localdiskrepo.o moc_localdiskrepo.cpp

moc_localstoragerepo.o: moc_localstoragerepo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localstoragerepo.o moc_localstoragerepo.cpp

moc_output.o: moc_output.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_output.o moc_output.cpp

moc_httpserver.o: moc_httpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpserver.o moc_httpserver.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_repodialog.o: moc_repodialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_repodialog.o moc_repodialog.cpp

moc_repomodel.o: moc_repomodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_repomodel.o moc_repomodel.cpp

moc_httprequest.o: moc_httprequest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httprequest.o moc_httprequest.cpp

moc_httpresponse.o: moc_httpresponse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpresponse.o moc_httpresponse.cpp

moc_httpclientrepo.o: moc_httpclientrepo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpclientrepo.o moc_httpclientrepo.cpp

moc_filetransfer.o: moc_filetransfer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filetransfer.o moc_filetransfer.cpp

moc_filetransfermanager.o: moc_filetransfermanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filetransfermanager.o moc_filetransfermanager.cpp

moc_httpmessage.o: moc_httpmessage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpmessage.o moc_httpmessage.cpp

moc_repo.o: moc_repo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_repo.o moc_repo.cpp

moc_readoncebuffer.o: moc_readoncebuffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_readoncebuffer.o moc_readoncebuffer.cpp

moc_httpcontroller.o: moc_httpcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpcontroller.o moc_httpcontroller.cpp

moc_statediff.o: moc_statediff.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statediff.o moc_statediff.cpp

qrc_icon.o: qrc_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icon.o qrc_icon.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

