######################################################################
# Automatically generated by qmake (2.01a) Wed May 12 12:52:24 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../output.h testoutput.moc
SOURCES += testoutput.cpp ../../output.cpp
