######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 15 07:10:34 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += httprequest.h
SOURCES += httprequest.cpp test-httprequest.cpp
