######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 16 20:18:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../filerepomanager.h
SOURCES += testfilerepomanager.cpp ../../filerepomanager.cpp
