######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 16 04:07:11 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../output.h testoutput.moc
SOURCES += testoutput.cpp ../../output.cpp
