# #####################################################################
# Automatically generated by qmake (2.01a) Wed Jun 16 04:07:29 2010
# #####################################################################
CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../workingfilerepo.h \
    testworkingfilerepo.moc
SOURCES += testworkingfilerepo.cpp \
    ../../workingfilerepo.cpp \
    testworkingfilerepo.cpp
